#..................................
#GitHub Action Part-1
#.................................
name: My-CitHub-Actions-Basics

on: 
  push: 
      branches:
          - master
jobs:
  my_testing:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello message
    - run: echo "Hello, world from Testing job"
  
  
  my_deploy:
  
    runs-on: ubuntu-latest
  
    steps:
    - name: Print Hello message
    - run: echo "Hello, world from Deploy job"
