services:
  prometheus:
    image: "prom/prometheus:v2.42.0"
    restart: unless-stopped
  grafana:
    image: "grafana/grafana:9.3.6"
    restart: unless-stopped
    environment:
      GF_SERVER_HTTP_PORT: 3000
    ports:
      - 8080:3000
  postgres:
    image: "postgres:14.7-alpine"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mydbpassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
