#..................................
#GitHub Action Part-1
#.................................
name: My-GitHub-Actions-Basics
env:
  APPLICATION_NAME    : "MyFlasc"
  DEPLOY_PACKAGE_NAME : "flasc-deploy-ver-${{ github.sha }}" 

on: 
  push: 
      branches:
          - main

jobs:
  my_testing:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello message in Testing
      run: echo "Hello, world from Testing job"
      
    - name: Execure few commands
      run: |
        echo "Hello message1"
        echo "Hello message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
    - name: List current folder
      run: ls -la
    
  my_deploy:
  
    runs-on: ubuntu-latest
    needs: [my_testing]
  
    steps:
    - name: Print Hello message in Deploy
      run: echo "Hello, world from Deploy job"
      
    - name: Printing Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
